=== asanzdiego/curso-interfaces-web-2020/01-usabilidad/src/03-analisis-de-tareas/concur-task-trees-environment/ctteCoop_v2.6.17/ctte.config/CTTDTD.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- This is the first version of Document Type Definition of the ConcurTaskTrees Notation --> 
<!-- We have reported only the semantic datas --> 
<!ELEMENT TaskModel (Task) >
<!ATTLIST TaskModel NameTaskModelID CDATA #REQUIRED >

<!ELEMENT Task (Name, Type, Description, Platform*, Precondition?, TemporalOperator?, TimePerformance, 
                Parent?, SiblingLeft?, SiblingRight?, Object*, SubTask*) >
<!ATTLIST Task Identifier CDATA #REQUIRED >
<!ATTLIST Task Category (abstraction | user | interaction | application) #REQUIRED >
<!ATTLIST Task Iterative (true | false) #REQUIRED >
<!ATTLIST Task Optional (true | false) #REQUIRED >
<!ATTLIST Task PartOfCooperation (true | false) #REQUIRED >
<!ATTLIST Task Frequency CDATA  #REQUIRED >
<!ELEMENT Name (#PCDATA) >
<!ELEMENT Type (#PCDATA) >
<!ELEMENT Description (#PCDATA) >


<!ELEMENT Platform (#PCDATA) >
<!ELEMENT Precondition (#PCDATA) >

<!ELEMENT TemporalOperator EMPTY >
<!ATTLIST TemporalOperator name (SequentialEnabling | Disabling | Choice | Interleaving | Synchronization | SuspendResume | SequentialEnablingInfo) #IMPLIED >

<!ELEMENT TimePerformance (Max, Min, Average) >
<!ELEMENT Max (#PCDATA) >
<!ELEMENT Min (#PCDATA) >
<!ELEMENT Average (#PCDATA) >
                             
<!ELEMENT Parent EMPTY >
<!ATTLIST Parent name CDATA #REQUIRED >
<!ELEMENT SiblingLeft EMPTY >
<!ATTLIST SiblingLeft name CDATA #REQUIRED >
<!ELEMENT SiblingRight EMPTY >
<!ATTLIST SiblingRight name CDATA #REQUIRED >

<!ELEMENT Object (Platform*, InputAction, OutputAction) >
<!ATTLIST Object name CDATA #REQUIRED >  
<!ATTLIST Object class (Text | Numerical | Object | Description | Position | null | string |decimal | integer | boolean | date | time) #REQUIRED >
<!ATTLIST Object type (Perceivable | Application | null)  #REQUIRED >
<!ATTLIST Object access_mode (Access | Modification | null) #REQUIRED >    
<!ATTLIST Object cardinality (Low | Medium | High | null) #REQUIRED >

<!ELEMENT InputAction EMPTY >
<!ATTLIST InputAction Description  CDATA #REQUIRED >
<!ATTLIST InputAction From  CDATA #REQUIRED >

<!ELEMENT OutputAction EMPTY >
<!ATTLIST OutputAction Description CDATA  #REQUIRED >
<!ATTLIST OutputAction To CDATA #REQUIRED >

<!ELEMENT SubTask (Task*) >

=== asanzdiego/curso-interfaces-web-2020/01-usabilidad/src/03-analisis-de-tareas/concur-task-trees-environment/ctteCoop_v2.6.17/Examples/xml/access-student-data.xml
<?xml version= '1.0'?>
<!DOCTYPE TaskModel PUBLIC "http://giove.cnuce.cnr.it/CTTDTD.dtd" "..\..\..\..\..\Documenti\NetBeansProjects\ctte\ctte.config\CTTDTD.dtd">

<TaskModel NameTaskModelID="C:\Documents and Settings\ari\Desktop\hiis tools\ctte\Examples\xml\access-student-data_2_3_3.xml">
<Task Identifier="AccessStudentData" Category="Abstraction Task" Iterative="false" Optional="false" PartOfCooperation="false" Frequency="null">
  <Name> null </Name>
  <Type>  </Type>
  <Description> null </Description>
  <Precondition> null </Precondition>
  <TimePerformance> 
   <Max> null </Max>
   <Min> null </Min>
   <Average> null </Average>
  </TimePerformance> 
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <SubTask>
<Task Identifier="ProvideRequest" Category="Interaction Task" Iterative="false" Optional="false" PartOfCooperation="false" Frequency="null">
  <Name> null </Name>
  <Type> null </Type>
  <Description> null </Description>
  <Precondition> null </Precondition>
  <TemporalOperator name="SequentialEnablingInfo"/>
  <TimePerformance> 
   <Max> null </Max>
   <Min> null </Min>
   <Average> null </Average>
  </TimePerformance> 
  <Parent name="AccessStudentData"/>
  <SiblingRight name="ShowResults"/>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <SubTask>
<Task Identifier="EnterParameters" Category="Interaction Task" Iterative="false" Optional="false" PartOfCooperation="false" Frequency="null">
  <Name> null </Name>
  <Type> null </Type>
  <Description> null </Description>
  <Precondition> null </Precondition>
  <TemporalOperator name="Disabling"/>
  <TimePerformance> 
   <Max> null </Max>
   <Min> null </Min>
   <Average> null </Average>
  </TimePerformance> 
  <Parent name="ProvideRequest"/>
  <SiblingRight name="SubmitRequest"/>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <SubTask>
<Task Identifier="EnterName" Category="Interaction Task" Iterative="true" Optional="false" PartOfCooperation="false" Frequency="null">
  <Name> null </Name>
  <Type> null </Type>
  <Description> null </Description>
  <Precondition> null </Precondition>
  <TemporalOperator name="Interleaving"/>
  <TimePerformance> 
   <Max> null </Max>
   <Min> null </Min>
   <Average> null </Average>
  </TimePerformance> 
  <Parent name="EnterParameters"/>
  <SiblingRight name="EnterDepartment"/>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  </Task>
<Task Identifier="EnterDepartment" Category="Interaction Task" Iterative="true" Optional="false" PartOfCooperation="false" Frequency="null">
  <Name> null </Name>
  <Type> null </Type>
  <Description> null </Description>
  <Precondition> null </Precondition>
  <TimePerformance> 
   <Max> null </Max>
   <Min> null </Min>
   <Average> null </Average>
  </TimePerformance> 
  <Parent name="EnterParameters"/>
  <SiblingLeft name="EnterName"/>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  </Task>
  </SubTask>
  </Task>
<Task Identifier="SubmitRequest" Category="Interaction Task" Iterative="false" Optional="false" PartOfCooperation="false" Frequency="null">
  <Name> null </Name>
  <Type> null </Type>
  <Description> null </Description>
  <Precondition> null </Precondition>
  <TimePerformance> 
   <Max> null </Max>
   <Min> null </Min>
   <Average> null </Average>
  </TimePerformance> 
  <Parent name="ProvideRequest"/>
  <SiblingLeft name="EnterParameters"/>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  </Task>
  </SubTask>
  </Task>
<Task Identifier="ShowResults" Category="Application Task" Iterative="false" Optional="false" PartOfCooperation="false" Frequency="null">
  <Name> null </Name>
  <Type> null </Type>
  <Description> null </Description>
  <Precondition> null </Precondition>
  <TimePerformance> 
   <Max> null </Max>
   <Min> null </Min>
   <Average> null </Average>
  </TimePerformance> 
  <Parent name="AccessStudentData"/>
  <SiblingLeft name="ProvideRequest"/>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  <Object name="" class="" type="" access_mode="" cardinality="">
  <InputAction Description="null" From="null"/>
  <OutputAction Description="null" To="null"/>
  </Object>
  </Task>
  </SubTask>
  </Task>
</TaskModel>
